# Generated by Django 2.2.24 on 2021-08-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taburl',
            name='nb',
            field=models.IntegerField(default=1),
        ),
    ]
