# Generated by Django 2.2.24 on 2021-08-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_taburl_nb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taburl',
            name='miniurl',
            field=models.CharField(max_length=9),
        ),
    ]
